#!/usr/bin/env bash

# Used load function from https://github.com/ArnoldasMk/Kali/blob/dev/Kali (modified) until I get a better understanding of gdb and injecting itself

# Check_For_logDirectory
csgo_pid=$(pidof csgo_linux64)
if [ -z "$csgo_pid" ]; then
    echo "CS:GO needs to be open before you can inject, exiting..."
    exit 1
fi

# pBypass for crash dumps being sent
# You may also want to consider using -nobreakpad in your launch options.
sudo rm -rf /tmp/dumps           # Remove if it exists
sudo mkdir --mode=000 /tmp/dumps # Make it as root with no permissions

filename="libcsgo-simple-linux-cheat.so"
libname="libMangoHud.so" # pretend to be something else

# Credit: Aixxe @ aixxe.net
if grep -q "$libname" /proc/"$csgo_pid"/maps; then
    echo "Already injected? Exiting..."
    exit
fi
echo "Injecting $filename from build directory..."

# https://www.kernel.org/doc/Documentation/security/Yama.txt
echo "2" | sudo tee /proc/sys/kernel/yama/ptrace_scope # Only allows root to inject code. This is temporary until reboot.

sudo cp "./build/$filename" "/usr/lib/${libname}"

sudo killall -19 steam
sudo killall -19 steamwebhelper

lib_dir_name="lib"
if [ $(getconf LONG_BIT) = 64 ]; then
    lib_dir_name+="64"
fi

input="$(
    sudo gdb -n -q -batch-silent \
        -ex "set logging on" \
        -ex "set logging file /dev/null" \
        -ex "set logging redirect on" \
        -ex "set auto-load safe-path /usr/share/gdb/auto-load/usr/$lib_dir_name/:/usr/$lib_dir_name/" \
        -ex "attach $csgo_pid" \
        -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
        -ex "call \$dlopen(\"/usr/lib/$libname\", 1)" \
        -ex "detach" \
        -ex "quit"
)"

sleep 1
sudo killall -18 steamwebhelper
sudo killall -18 steam

last_line="${input##*$'\n'}"

if [ "$last_line" != "\$1 = (void *) 0x0" ]; then
    echo "Successfully injected!"
else
    echo "Injection failed!"
fi