#!/usr/bin/env bash

# Used unload function from https://github.com/ArnoldasMk/Kali/blob/dev/Kali

csgo_pid=$(pidof csgo_linux64)
filename="libcsgo-simple-linux-cheat.so"

echo "Unloading cheat..."
echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
if grep -q "$filename" /proc/"$csgo_pid"/maps; then
    echo "unloading $filename"
    sudo gdb -n -q -batch-silent \
        -ex "set logging on" \
        -ex "set logging file /dev/null" \
        -ex "set logging redirect on" \
        -ex "attach $csgo_pid" \
        -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
        -ex "set \$dlclose = (int(*)(void*)) dlclose" \
        -ex "set \$library = \$dlopen(\"/usr/lib/$filename\", 6)" \
        -ex "call \$dlclose(\$library)" \
        -ex "call \$dlclose(\$library)" \
        -ex "detach" \
        -ex "quit"
    sudo rm "/usr/lib/${filename}"
fi
echo "Unloaded!"